More accurate jfrog setup to prevent skipping artifactoryDeploy for some subprojects
octopusden/octopus-rm-gradle-plugin pull request #59
Opened 2024-11-26 18:33 UTC by fishinitself

This fixes the following bug - in case of particular gradle project with a few subprojects, one of subprojects didn't deploy its results to artifactory. This was caused by late applying and configuring com.jfrog.artifactory to subprojects

2024-12-11 07:07 UTC, pgorbachev commented on ft/src/test/resources/publish/multi-module-regression/gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-8.10.2-all.zip
8.11.1

2024-12-11 11:43 UTC, pgorbachev commented on ft/src/test/resources/publish/multi-module-regression/rmtest-core/src/main/java/org/octopusden/rmtest/core/utils/StringPair.java
> +public class StringPair implements Map.Entry<String, String> {
Для чего нужен этот класс?

2024-12-11 11:57 UTC, pgorbachev requested changes
Предлагаю почистить тестовый проект

2024-12-11 12:27 UTC, fishinitself commented on ft/src/test/resources/publish/multi-module-regression/rmtest-core/src/main/java/org/octopusden/rmtest/core/utils/StringPair.java
> +public class StringPair implements Map.Entry<String, String> {
Да куда уже меньше... Ну ок, упростил

2024-12-11 12:44 UTC, ozonophore approved these changes

2024-12-12 18:23 UTC, pgorbachev approved these changes

2024-12-16 07:03 UTC, CamaradeRoman approved these changes

2024-12-16 09:28 UTC, merged